### ISSUE TITLE
Mejorar iconito de la web (para mobiles)

### ISSUE THREAD

**Issue by rusosnith** [goncy/trency#1]
Ahora que tiene posibilidad de linkear directo a una estación es muy util para tenerlo shortcuteado en el celular, pero el icono (y el nombre demasiado largo) hacen que sea poco intuitivo el icono. 

se puede usar algo de thenounproject o de materialdesignicons!

![image](https://cloud.githubusercontent.com/assets/4212247/24049819/ddefad76-0b0b-11e7-9eab-e012065bb4ed.png)

**Comment by goncy** [comment]
El favicon es el default de React, podria armar algo, el nombre es el title de la pagina no? voy a buscar si hay algun metatag para ese name, gracias!

**Comment by goncy** [comment]
Ahi deberia estar, no encontre el meta para el name (creo), pero meti algunos, porfa chequeame si se ve mejor!
